import {
  SiHtml5,
  SiCss,
  SiSass,
  SiBootstrap,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiRedux,
  SiReactquery,
  SiMui,
  SiRadixui,
  SiSocketdotio,
  SiWebpack,
  SiVite,
  SiGit,
  SiGithub,
  SiGitlab,
  SiFigma,
  SiNodedotjs,
  SiNestjs,
  SiPostgresql,
  SiPrisma,
  SiDocker,
  SiNginx,
  SiJest,
  SiCypress,
  SiLinux,
  SiStyledcomponents,
  SiJsonwebtokens,
  SiK6,
  SiOctopusdeploy,
} from "react-icons/si";

import {
  TbApi,
  TbBrandNextjs,
  TbCube,
  TbTopologyStar3,
} from "react-icons/tb";
import { MdStorage, MdEmail } from "react-icons/md";
import { FaLanguage } from "react-icons/fa";
import type { ReactNode } from "react";

export const techIcons: Record<string, ReactNode> = {
  html: <SiHtml5 color="#E34F26" />,
  css: <SiCss color="#1572B6" />,
  sass: <SiSass color="#CC6699" />,
  bootstrap: <SiBootstrap color="#7952B3" />,
  javascript: <SiJavascript color="#F7DF1E" />,
  typescript: <SiTypescript color="#3178C6" />,
  react: <SiReact color="#61DAFB" />,
  nextjs: <SiNextdotjs color="#FFFFFF" />,
  redux: <SiRedux color="#764ABC" />,
  reactQuery: <SiReactquery color="#FF4154" />,
  nextAuth: <TbBrandNextjs color="#FFFFFF" />,
  styledComponents: <SiStyledcomponents color="#DB7093" />,
  mui: <SiMui color="#007FFF" />,
  radix: <SiRadixui color="#FFFFFF" />,
  socketio: <SiSocketdotio color="#FFFFFF" />,
  webpack: <SiWebpack color="#8DD6F9" />,
  vite: <SiVite color="#646CFF" />,
  api: <TbApi color="#D7FF35" />,
  fsd: <TbTopologyStar3 color="#D7FF35" />,
  git: <SiGit color="#F05032" />,
  github: <SiGithub color="#FFFFFF" />,
  gitlab: <SiGitlab color="#FC6D26" />,
  figma: <SiFigma color="#F24E1E" />,
  english: <FaLanguage color="#D7FF35" />,
  nodejs: <SiNodedotjs color="#5FA04E" />,
  nestjs: <SiNestjs color="#E0234E" />,
  postgresql: <SiPostgresql color="#4169E1" />,
  prisma: <SiPrisma color="#FFFFFF" />,
  jwt: <SiJsonwebtokens color="#FFFFFF" />,
  s3: <MdStorage color="#569A31" />,
  smtp: <MdEmail color="#EA4335" />,
  docker: <SiDocker color="#2496ED" />,
  dockerCompose: <TbCube color="#2496ED" />,
  nginx: <SiNginx color="#009639" />,
  linux: <SiLinux color="#FCC624" />,
  deploy: <SiOctopusdeploy color="#2F93E0" />,
  jest: <SiJest color="#C21325" />,
  cypress: <SiCypress color="#69D3A7" />,
  k6: <SiK6 color="#7D64FF" />,
};
